
- name: Configuration deployment
  hosts: FABRIC # <-- Targeted devices
  connection: local
  gather_facts: false
  tasks:
    - name: Deploy configurations and tags to CloudVision
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        cv_server: 10.18.179.244
        cv_token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjc2MTgwMTY2MzcxNzc4MjM1MDUsImRzbiI6IkFWRCIsImRzdCI6ImFjY291bnQiLCJleHAiOjE3NzQ4NzU3MTksImlhdCI6MTc3MzcxOTQ5NSwib2dpIjozLCJvZ24iOiJEZWZhdWx0Iiwic2lkIjoiYzcwN2U0YmY1NDA5OTYzZjk1ZjMwYzU5OTNmNWViZGFkNjZiMzQ2YzIyMmU3NjEzODMwNTE0YTRjYmIxYzk4Mi0takM4YUNZVlhxOExJV0ZwMElmTEY5WDMyVWQ3X0R3NFRhdU51OEdNIn0.g5EckP5mvSxKZAP0E2Odb_05RGJsiXRlbqpoIm-4T6resGYWt_SdTPPFwogNjl6-bhtlY-3LjNXwiR9vHMr6G15VIw3DvQpweOyaoTA1mjcc2ZNGd7exwpbgEQYDR3q5sFK4lzj9JBgg_5oUKDvcOFNV6a1h5U8FWYXGXzEt7ltiKcCNjsTdpEYPklpnbg9sn2ZYO-nVZ-y-uz3KUAWekr0icnO4FSmKkMyhYHBIDerVfzSA64KZVOZg2y99_YR9OmoZdt3aL_Macj6NUfgi20Obz_YGj1w8p1HYq_8zLn4i3Q2Tz7RnAWx6HClNIsUEVw3mLnrt3rH7SDJgue6q-RGY8uXCJirPkT5jTNRAcGRoZK8N-UP9w2mpeThinjZnED93XSDIhbhk59-fr0SiQ1V1sTdiry5Ddr6QnV-Wogfq6Uin9WnwPE4G34m7oxL5vCdauPLRpbS4Cu0b8chR2BmOjSYBMrudj5yBvkndilgm3SXZx4jwyi03DEKBnMDneYoqxtCUqmkOfVS4nteIymYJgRn9bCCWgzic61MD-4XCXsbtmB3_nNsT8oFrLQXwVElSCYw1MmOtcNXSK_tA7xWUN-uXfAvRfNVLHIB_7X2ygvyuKPHu358eIS0mIEjYExVdG26uXr9UcpFmK2MDUdlYbUsPzKQeH31vin2qQPU
        cv_verify_certs: false
