
- name: Configuration deployment
  hosts: FABRIC # <-- Targeted devices
  connection: local
  gather_facts: false
  tasks:
    - name: Deploy configurations and tags to CloudVision
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        cv_server: 10.18.179.11
        cv_token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjc2MTc5OTYzMDkwOTc2MTE1MzcsImRzbiI6IkFWRCIsImRzdCI6ImFjY291bnQiLCJleHAiOjE3NzQ4NzU2MDAsImlhdCI6MTc3MzcxNDMyMCwib2dpIjozLCJvZ24iOiJEZWZhdWx0Iiwic2lkIjoiODc2MmZhZWY2NGYwYTAyMTY1YWRjZDkzMzBjNjE0YTMzYzlmNjA5MzlkYTc5MGRlZDI3YmE5MzQ0ZjAzMGRiMi1uQW1FNmVVWGlIazRNVmM2VF9LT09FUzZSU2NONE5NbUI0U3VOUXhGIn0.YivUyHS3hVnduRqmjij_ncxGevVk9XsJS3leG7EL6FCUSidSjVqc9n-PiMFknhybvCr4WWmwHOHxlTmuU0SzyJzbw7T_B_XeZ_6lN7uYaa8eYj6BMtrA_frj5yymma5tGpV-4AlP-fPF70HRBugIuYe150sCk2AW_zcsY9lVDC7flejqi0LpZFVVSJxZO0YpFe77n_NImax_G-pGSBY9fatpTzSuOE7FFGnsLySsJeybgtAU-sbzHfPZPlpILsAAj40vBp_nEguEL7eMgvYnyWNCQqCGEr63dEvcS7P39OC1UTmhKpFNjf3E2gFN78xeLYdwnAAd9VBBcYjTnsZEABWBOUItdcTdeYbg83Wz4_o6yvm79lODLtJBhHf1jYM9I-k0zuVGBSfac-QxuPLboRnGqMGm2dUgghW01zcSko-q5r6FerkkxaEbanIzgCBLfLTJ16EpN07lMWRRCB0dH2tgRosoCw5PlD6Gwlj9o37haAxeYIWswberUQyK1C8gKn6aHFKxukWu_go7aJgAZ-LZU9Kc8lSarYEqJxkqmJAEnYUaBlBj7H0Y0mRwdLfqmhFLe3jjopMUDSkcgEg6X9vB02fxIALx-ZofZMJp6YCAhWV4_Uc_qdfJnU2C-klIydAwUV9Jv-NB4jJkaIdVea6xZvImZU90BpYFSJSJ-vw
        cv_verify_certs: false
