---

fabric_name: FABRIC

# Various fabric settings

# Ansible connectivity definitions
# eAPI connectivity via HTTPS is specified (as opposed to CLI via SSH)
ansible_connection: ansible.netcommon.httpapi
# Specifies that we are indeed using Arista EOS
ansible_network_os: arista.eos.eos
# This user/password must exist on the switches to enable Ansible access
ansible_user: arista
ansible_password: "Arista123!"
# User escalation (to enter enable mode)
ansible_become: true
ansible_become_method: enable
# Use SSL (HTTPS)
ansible_httpapi_use_ssl: true
# Do not try to validate certs
ansible_httpapi_validate_certs: false


# Enable vlan aware bundles
evpn_vlan_aware_bundles: false
mgmt_gateway: 192.168.0.5
mgmt_interface_vrf: default


# Local users
aaa_settings.local_users:
  # Define a new user, which is called "ansible"
  - name: ansible
    privilege: 15
    role: network-admin
    # Password set to "ansible". Same string as the device generates when configuring a username.
    sha512_password: $6$7u4j1rkb3VELgcZE$EJt2Qff8kd/TapRoci0XaIZsL4tFzgq1YZBLD9c6f/knXzvcYY0NcMKndZeCv0T268knGKhOEwZAxqKjlMm920
  - name: admin
    privilege: 15
    role: network-admin
    no_password: true
# There's an issue with vEOS with larger MTUs
p2p_uplinks_mtu: 1550

# BFD Settings
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3


# Needed for vEOS/cEOS

bgp_update_wait_install: false
bgp_update_wait_for_convergence: false

# Needed for Arista ATD Lab Environment
#dns_domain: atd.lab
#mgmt_interface: Management0
#mgmt_interface_vrf: MGMT
#mgmt_gateway: 192.168.0.1

# L3 Edge port definitions. This can be any port in the entire Fabric, where IP interfaces are defined.
l3_edge:
  # Define a new IP pool that will be used to assign IP addresses to L3 Edge interfaces.
  p2p_links_ip_pools:
    - name: DCI_IP_pool
      ipv4_pool: 172.100.100.0/22
  # Define a new link profile which will match the IP pool, the used ASNs and include the defined interface into underlay routing
  p2p_links_profiles:
    - name: DCI_profile
      ip_pool: DCI_IP_pool
      as: [65110, 65210]
      include_in_underlay_protocol: true
  # Define each P2P L3 link and link the nodes, the interfaces and the profile used.
  p2p_links:
    - id: 101
      nodes: [dc1-borderleaf1, dc2-borderleaf1]
      interfaces: [Ethernet20, Ethernet20]
      profile: DCI_profile
    - id: 202
      nodes: [dc1-borderleaf2, dc2-borderleaf2]
      interfaces: [Ethernet20, Ethernet20]
      profile: DCI_profile
